############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Chi Sono"
url = "chi-sono/"
weight = 2

[[main]]
name = "Arte"
weight = 4
hasChildren = true
[[main]]
parent = "Arte"
name = "Sculture"
url = "sculture/"
weight = 1
[[main]]
parent = "Arte"
name = "Musica"
url = "musica/"
weight = 2
[[main]]
parent = "Arte"
name = "Racconti"
url = "racconti/"
weight = 3

[[main]]
name = "Web Design"
weight = 4
hasChildren = true
[[main]]
parent = "Web Design"
name = "Servizi Web"
url = "https://reineristudio.com"
weight = 1
[[main]]
parent = "Web Design"
name = "Freelance"
url = "/freelance"
weight = 2

[[main]]
name = "Contatti"
url = "contatti/"
weight = 7

# footer menu
[[footer]]
name = "Chi Sono"
url = "chi-sono/"
weight = 1

[[footer]]
name = "Web Design"
url = "https://reineristudio.com/"
weight = 2

[[footer]]
name = "Sculture"
url = "sculture/"
weight = 3

[[footer]]
name = "Musica"
url = "musica/"
weight = 4

[[footer]]
name = "Racconti"
url = "racconti/"
weight = 5

[[footer]]
name = "Contatti"
url = "contatti/"
weight = 6

