############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Chi Sono"
url = "chi-sono/"
weight = 2

[[main]]
name = "Arte"
weight = 4
hasChildren = true
[[main]]
parent = "Arte"
name = "Sculture"
url = "sculture/"
weight = 1
[[main]]
parent = "Arte"
name = "Musica"
url = "musica/"
weight = 2
[[main]]
parent = "Arte"
name = "Racconti"
url = "racconti/"
weight = 3

[[main]]
name = "Programmazione"
weight = 3
hasChildren = true
[[main]]
parent = "Programmazione"
name = "Servizi Web"
url = "https://reineristudio.com"
weight = 1
[[main]]
parent = "Programmazione"
name = "Freelance"
url = "https://albertoreineri.github.io"
weight = 2


[[main]]
name = "Blog"
url = "blog/"
weight = 6

[[main]]
name = "Contatti"
url = "contatti/"
weight = 7

# footer menu
[[footer]]
name = "Chi Sono"
url = "chi-sono/"
weight = 1

[[footer]]
name = "Sculture"
url = "sculture/"
weight = 2

[[footer]]
name = "Musica"
url = "musica/"
weight = 3

[[footer]]
name = "Blog"
url = "blog/"
weight = 4

[[footer]]
name = "Contatti"
url = "contatti/"
weight = 5

