############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Chi Sono"
url = "chi-sono/"
weight = 2

[[main]]
name = "Web Design"
url = "https://reineristudio.com"
weight = 3

[[main]]
name = "Sculture"
url = "sculture/"
weight = 4

[[main]]
name = "Musica"
url = "musica/"
weight = 5

[[main]]
name = "Blog"
url = "blog/"
weight = 6

[[main]]
name = "Contatti"
url = "contatti/"
weight = 7

# footer menu
[[footer]]
name = "Chi Sono"
url = "chi-sono/"
weight = 1

[[footer]]
name = "Sculture"
url = "sculture/"
weight = 2

[[footer]]
name = "Musica"
url = "musica/"
weight = 3

[[footer]]
name = "Blog"
url = "blog/"
weight = 4

[[footer]]
name = "Contatti"
url = "contatti/"
weight = 5

